name: Test
on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.0'
     
      - name: Install dependencies
        run: pip install -r requirements.txt 

      - name: Run test
        run: pytest 

      - name: "install Snyk"
        shell: bash
        run: |
          npm install -g snyk
            
